version: '3.8'
services:
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: farmacia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: docker.io/library/mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  pacientes:
    build:
      context: ./pacientes
    container_name: pacientes
    depends_on:
      - postgres
      - kafka
    env_file:
      - ./pacientes/.env
    ports:
      - "8000:8000"

  inventario:
    build:
      context: ./inventario
    container_name: inventario
    depends_on:
      - postgres
      - kafka
    env_file:
      - ./inventario/.env
    ports:
      - "8001:8001"

  visual:
    build:
      context: ./visual
    container_name: visual
    depends_on:
      - postgres
      - kafka
    env_file:
      - ./visual/.env
    ports:
      - "8002:8002"


  frontend: # <-- NUEVO SERVICIO
    build:
      context: ./frontend # Ruta a la carpeta donde est치 el Dockerfile del frontend
    container_name: frontend
    ports:
      - "3000:80" # Expone el puerto 80 del contenedor Nginx al puerto 3000 de tu m치quina host
                  # Puedes elegir otro puerto host si el 3000 est치 ocupado, ej. "8081:80"
    depends_on:
      - pacientes # Opcional, pero asegura que el backend se inicie antes, aunque no es estrictamente necesario para servir archivos est치ticos.

volumes:
  pgdata:
  mongodata:
